REFILL_DISTANCE_THRESHOLD = 22
MOTION_DISTANCE_THRESHOLD = 10

ULTRASONIC_TRIGGER_PET = 38
ULTRASONIC_ECHO_PET = 40
ULTRASONIC_TRIGGER_DISPENSER_ONE = 29
ULTRASONIC_ECHO_DISPENSER_ONE = 37
ULTRASONIC_TRIGGER_DISPENSER_TWO = 32
ULTRASONIC_ECHO_DISPENSER_TWO = 36

STEPPER_CHANNEL_ONE = (12, 16, 18, 22)
STEPPER_CHANNEL_TWO = (7, 11, 13, 15)