TIME_TO_DISPENSE_PET_ONE = 5
TIME_TO_DISPENSE_PET_TWO = 5

REFILL_DISTANCE_THRESHOLD = 20
MOTION_DISTANCE_THRESHOLD = 30

ULTRASONIC_TRIGGER_PET = 18
ULTRASONIC_ECHO_PET = 24
# ULTRASONIC_TRIGGER_DISPENSER_ONE = 
# ULTRASONIC_ECHO_DISPENSER_ONE = 
# ULTRASONIC_TRIGGER_DISPENSER_TWO = 
# ULTRASONIC_ECHO_DISPENSER_TWO = 

# STEPPER_CHANNEL_ONE = (22, 27, 17, 4)
# STEPPER_CHANNEL_TWO = 